logging:
  level: INFO
  loggers:
    org.lelik: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: h2
      port: 8080
      keyStorePath: keystore # required
      keyStorePassword: 12345678
