logging:
  level: INFO
  loggers:
    com.oracle.ugbu.opower: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: h2
      port: 8085
      keyStorePath: keystore # required
      keyStorePassword: 12345678
