logging:
  level: INFO
  loggers:
    org.lelik: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
    - type: h2 #http2 protocol connection
      port: 8085
      keyStorePath: ${KEYSTORE_PATH} # required
      keyStorePassword: ${KEYSTORE_PASSWORD}
